services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: farm-api:local
    container_name: api
    ports:
      - "3001:3001"
    env_file: ./backend/.env
    volumes:
      - /opt/app/uploads:/app/uploads
    restart: always
